### ISSUE TITLE
For mor concern separated the binary file must be separated from the lib

### ISSUE THREAD

**Issue by khrlimam** [daudmalik06/PhpScreenRecorder#3]
The binary file must be separated from the lib itself, so the binary have their own explanation about how to use them. For example in Linux i have to make the binary executable after being downloaded. with command `chmod +x filename`, so for the cleaner solution separating binary and having their own docs of how to install them in computer to me is clean and the lib itself isn't large enough to be downloaded especially if I already have `ffmpeg` installed on my computer.

**Comment by daudmalik06** [comment]
yeah , there are several pros and cons 
have to think about it .
