### ISSUE TITLE
stopRecording thows "Some error occurred during recording, verify your provided options"

### ISSUE THREAD

**Issue by botmike** [daudmalik06/PhpScreenRecorder#4]
Some error occurred during recording, verify your provided options
#0 /usr/local/Zend/ZendStudio/m/php_auto/Selenium/Tests/Debug/JsErrorTest.php(33): dawood\PhpScreenRecorder\ScreenRecorder->stopRecording(0)

Running on Ubuntu 16.04
I've set the binary "ffmpegLinux" to allow executing

When running this, every thing seems to start fine (I was debugging a bit)

startRecording
$this->process->getPid() ; // prints out a real number

stopRecording
$this->process->getPid(); // does not print out a real number

So it seems like the binarry starts up, but by the time I get to end the recordering the pid is already dead.  No video is saved

The test I used was fairly simple:
		$this->screenRecorder->setScreenSizeToCapture(1920,1080);
		$this->screenRecorder->startRecording('/var/www/selenium_results.local/data/movies/bl44a.flv', 2);	
		$driver = $this->webDriver;
		$driver->get('http://selenium_results.local/script_err.php');
		$this->screenRecorder->stopRecording(0);

Is there any other debuging information I can pull out (if the bin fails does it have a log file some where?)

**Comment by daudmalik06** [comment]
hello , sorry for late reply i was bit busy , 
well did you check if  `ffmpegLinux` binary  is correct and executes when you try to execute it directly from cli ?

further you can check the final command created by library as following
`$this->process->getCommandLine()`
and try executing that command , 

best regards
